# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34b08521a5cfd8e01015201e289ef545"
name = "second-try"
handle = "second-try-5"
application_url = "https://know-greatest-intranet-consultants.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-youtubee.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://know-greatest-intranet-consultants.trycloudflare.com/auth/callback",
  "https://know-greatest-intranet-consultants.trycloudflare.com/auth/shopify/callback",
  "https://know-greatest-intranet-consultants.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
